FROM node:12-alpine

ENV NODE_ENV=development


USER node
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY ./package.json .
RUN npm install

COPY . .

CMD [ "./node_modules/.bin/nodemon", "--config", "nodemon.json", "bin/www" ]